http:  
  port: "![7lfNJW6/zOc=]"
database:
  uhub:    
    host: "![sn0/bkKC48z/NTUjMAQSqg==]"
    port: "![IYFYwfs4WCI=]"   
    user: "![jvQys9l5oL8=]"
    password: "![L9748NlaZ6u/yzK3xnARRA==]"
    instance: "![JnfuSpVw020=]"